#!/bin/sh
set -e

# change dir permission
chmod -R 0777 "$FORUM_PROJECT_ROOT/storage" "$FORUM_PROJECT_ROOT/bootstrap/cache"

until mysqladmin ping -h "$DB_HOST"; do
    sleep 2;
done

# cache config
php artisan config:cache

# cache route
#php artisan route:cache

php artisan migrate --force --step

# first arg is `-f` or `--some-option`
if [ -z "$1" ] || [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

exec "$@"
